# Data Collection

## `pybaseball` Package Demonstration

### FanGraphs Stats (by year)

#### Batting

In [ ]:
from pybaseball import batting_stats  # This worked before 4/22/26, but now there are restrictions

In [2]:
# 2024
df_bat = batting_stats(2024, qual = 0)  # Set qual = 0 to get all players
print("2024 batting stats:\n")
df_bat.head()

2024 batting stats:

,IDfg,Season,Name,Team,Age,G,AB,PA,H,1B,...,maxEV,HardHit,HardHit%,Events,CStr%,CSW%,xBA,xSLG,xwOBA,L-WAR
4,15640,2024,Aaron Judge,NYY,32,158,559,704,180,85,...,117.5,239.0,0.611,391,0.146,0.267,0.305,0.740,0.481,11.7
13,25764,2024,Bobby Witt Jr.,KCR,24,161,636,709,211,123,...,116.9,260.0,0.483,538,0.138,0.236,0.309,0.583,0.407,10.5
8,19755,2024,Shohei Ohtani,LAD,29,159,636,731,197,98,...,119.2,288.0,0.598,482,0.144,0.269,0.310,0.672,0.444,9.3
9,20123,2024,Juan Soto,NYY,25,157,576,713,166,90,...,115.7,262.0,0.568,461,0.189,0.263,0.311,0.656,0.464,8.2
29,26289,2024,Gunnar Henderson,BAL,23,159,630,719,177,102,...,113.1,256.0,0.539,475,0.167,0.265,0.279,0.499,0.374,8.1

#### Pitching

In [ ]:
from pybaseball import pitching_stats  # This worked before 4/22/26, but now there are restrictions

In [4]:
# 2024
df_pitch = pitching_stats(2024, qual = 0)
print("2024 pitching stats:\n")
df_pitch.head()

2024 pitching stats:

,IDfg,Season,Name,Team,Age,W,L,WAR,ERA,G,...,Pit+ FC,Stf+ FS,Loc+ FS,Pit+ FS,Stuff+,Location+,Pitching+,Stf+ FO,Loc+ FO,Pit+ FO
130,10603,2024,Chris Sale,ATL,35,18,3,6.4,2.38,29,...,NaN,NaN,NaN,NaN,104,111,110,NaN,NaN,NaN
131,22267,2024,Tarik Skubal,DET,27,18,4,6.0,2.39,31,...,NaN,NaN,NaN,NaN,112,100,112,NaN,NaN,NaN
144,10310,2024,Zack Wheeler,PHI,34,16,7,5.4,2.57,32,...,96.0,94.0,101.0,91.0,110,104,113,NaN,NaN,NaN
226,21846,2024,Cole Ragans,KCR,26,11,9,4.9,3.14,32,...,100.0,NaN,NaN,NaN,110,99,110,NaN,NaN,NaN
211,12447,2024,Seth Lugo,KCR,34,16,9,4.7,3.00,33,...,108.0,86.0,100.0,78.0,97,100,97,NaN,NaN,NaN

#### Fielding

In [ ]:
from pybaseball import fielding_stats  # This worked before 4/22/26, but now there are restrictions

In [6]:
# 2024
df_field = fielding_stats(2024, qual = 0)
print("2024 fielding stats:\n")
df_field.head()

2024 fielding stats:

,IDfg,Season,Name,Team,Pos,G,GS,Inn,PO,A,...,60-90%,# 60-90%,90-100%,# 90-100%,rSZ,rCERA,rTS,FRM,OAA,Range
0,27478,2024,Patrick Bailey,SFG,C,115,101,908.0,904,55,...,NaN,NaN,NaN,NaN,15.0,1.0,NaN,23.7,NaN,NaN
1,21534,2024,Cal Raleigh,SEA,C,135,125,1122.0,1138,51,...,NaN,NaN,NaN,NaN,11.0,3.0,NaN,12.9,NaN,NaN
2,19452,2024,Jake Rogers,DET,C,92,86,761.0,744,29,...,NaN,NaN,NaN,NaN,9.0,2.0,NaN,13.6,NaN,NaN
3,22581,2024,Alejandro Kirk,TOR,C,93,89,766.0,706,46,...,NaN,NaN,NaN,NaN,7.0,-1.0,NaN,9.2,NaN,NaN
4,27562,2024,Austin Wells,NYY,C,110,96,872.1,892,33,...,NaN,NaN,NaN,NaN,7.0,0.0,NaN,10.5,NaN,NaN

#### Standings

In [7]:
from pybaseball import standings

In [8]:
# 2024
stand = standings(2024)
print("2024 standings:\n")
print(stand, "\n\n")
print(type(stand))

2024 standings:

[                  Tm   W   L  W-L%    GB
1   New York Yankees  94  68  .580    --
2  Baltimore Orioles  91  71  .562   3.0
3     Boston Red Sox  81  81  .500  13.0
4     Tampa Bay Rays  80  82  .494  14.0
5  Toronto Blue Jays  74  88  .457  20.0,                     Tm   W    L  W-L%    GB
1  Cleveland Guardians  92   69  .571    --
2   Kansas City Royals  86   76  .531   6.5
3       Detroit Tigers  86   76  .531   6.5
4      Minnesota Twins  82   80  .506  10.5
5    Chicago White Sox  41  121  .253  51.5,                    Tm   W   L  W-L%    GB
1      Houston Astros  88  73  .547    --
2    Seattle Mariners  85  77  .525   3.5
3       Texas Rangers  78  84  .481  10.5
4   Oakland Athletics  69  93  .426  19.5
5  Los Angeles Angels  63  99  .389  25.5,                       Tm   W    L  W-L%    GB
1  Philadelphia Phillies  95   67  .586    --
2         Atlanta Braves  89   73  .549   6.0
3          New York Mets  89   73  .549   6.0
4   Washington Nationals  71   91  .438  24.0
5          Miami Marlins  62  100  .383  33.0,                     Tm   W   L  W-L%    GB
1    Milwaukee Brewers  93  69  .574    --
2         Chicago Cubs  83  79  .512  10.0
3  St. Louis Cardinals  83  79  .512  10.0
4      Cincinnati Reds  77  85  .475  16.0
5   Pittsburgh Pirates  76  86  .469  17.0,                      Tm   W    L  W-L%    GB
1   Los Angeles Dodgers  98   64  .605    --
2      San Diego Padres  93   69  .574   5.0
3  Arizona Diamondbacks  89   73  .549   9.0
4  San Francisco Giants  80   82  .494  18.0
5      Colorado Rockies  61  101  .377  37.0]


<class 'list'>

Note: The output here is a list, not a Pandas `DataFrame`!

### Statcast Data (by date range)

#### All Players

In [9]:
from pybaseball import statcast

In [33]:
# April 2024
df_april_2024 = statcast(start_dt = "2024-04-01", end_dt = "2024-04-30")
print("\n\nStatcast data for April 2024:\n")
df_april_2024.head()

This is a large query, it may take a moment to complete

100%|██████████| 30/30 [00:00<00:00, 37.89it/s]

Statcast data for April 2024:

,pitch_type,game_date,release_speed,release_pos_x,release_pos_z,player_name,batter,pitcher,events,description,...,batter_days_until_next_game,api_break_z_with_gravity,api_break_x_arm,api_break_x_batter_in,arm_angle,attack_angle,attack_direction,swing_path_tilt,intercept_ball_minus_batter_pos_x_inches,intercept_ball_minus_batter_pos_y_inches
2758,CH,2024-04-30,81.2,-2.75,5.42,"Crismatt, Nabil",572233,622503,home_run,hit_into_play,...,1,3.26,0.77,0.77,30.6,12.403026,-15.416753,30.24036,27.331381,38.061986
2864,CH,2024-04-30,81.4,-2.73,5.47,"Crismatt, Nabil",572233,622503,None,ball,...,1,2.94,0.43,0.43,30.0,<NA>,<NA>,<NA>,<NA>,<NA>
2975,CH,2024-04-30,82.0,-2.63,5.6,"Crismatt, Nabil",572233,622503,None,called_strike,...,1,3.04,0.68,0.68,34.1,<NA>,<NA>,<NA>,<NA>,<NA>
2415,SL,2024-04-30,87.8,-1.57,6.03,"McGough, Scott",606192,543518,field_out,hit_into_play,...,1,2.62,-0.36,-0.36,46.3,9.609388,3.140277,28.265415,36.588029,26.726277
2453,FF,2024-04-30,93.6,-1.49,6.03,"McGough, Scott",606192,543518,None,ball,...,1,1.0,0.66,0.66,45.2,<NA>,<NA>,<NA>,<NA>,<NA>

Note: This extraction, using the `statcast` function, gets pitch-level data, hence why there is a warning that it's a large query when the code is executed! A different function that pulls aggregated data is used for the project!

#### One Player

In [11]:
from pybaseball import playerid_lookup, statcast_batter

In [32]:
# Search for Aaron Judge IDs
judge_ids = playerid_lookup("Judge", "Aaron")
print("Aaron Judge IDs:\n") 
print(judge_ids, "\n\n")

# Pull Statcast data for Aaron Judge in April 2024
df_judge = statcast_batter("2024-04-01", "2024-04-30", 592450)
print("Statcast data for Aaron Judge in April 2024:\n")
df_judge.head()

Aaron Judge IDs:

  name_last name_first  key_mlbam key_retro  key_bbref  key_fangraphs  \
0     judge      aaron     592450  judga001  judgeaa01          15640

   mlb_played_first  mlb_played_last
0            2016.0           2025.0


Statcast data for Aaron Judge in April 2024:

,pitch_type,game_date,release_speed,release_pos_x,release_pos_z,player_name,batter,pitcher,events,description,...,batter_days_until_next_game,api_break_z_with_gravity,api_break_x_arm,api_break_x_batter_in,arm_angle,attack_angle,attack_direction,swing_path_tilt,intercept_ball_minus_batter_pos_x_inches,intercept_ball_minus_batter_pos_y_inches
0,FS,2024-04-30,84.4,-2.10,5.90,"Judge, Aaron",592450,665152,walk,ball,...,1,3.01,0.73,0.73,33.3,NaN,NaN,NaN,NaN,NaN
1,FS,2024-04-30,84.4,-1.98,5.83,"Judge, Aaron",592450,665152,None,ball,...,1,2.81,0.66,0.66,37.9,NaN,NaN,NaN,NaN,NaN
2,SI,2024-04-30,94.4,-1.96,5.72,"Judge, Aaron",592450,665152,None,foul,...,1,1.64,1.26,1.26,36.9,-1.682816,6.29889,40.772598,46.311133,20.648277
3,FC,2024-04-30,87.9,-2.01,6.03,"Judge, Aaron",592450,665152,None,called_strike,...,1,2.38,-0.22,-0.22,40.5,NaN,NaN,NaN,NaN,NaN
4,FC,2024-04-30,88.5,-1.92,6.14,"Judge, Aaron",592450,665152,None,ball,...,1,2.31,-0.48,-0.48,40.2,NaN,NaN,NaN,NaN,NaN

Note: Notice how there are different IDs for FanGraphs and Statcast (MLBAM)! This becomes important for the project below!

### Team Stats

#### Schedule and Record

In [13]:
from pybaseball import schedule_and_record

In [31]:
# Yankees 2024
df_nyy_2024 = schedule_and_record(2024, "NYY")
print("Yankees 2024 schedule and record:\n")
df_nyy_2024.head()

Yankees 2024 schedule and record:

,Date,Tm,Home_Away,Opp,W/L,R,RA,Inn,W-L,Rank,GB,Win,Loss,Save,Time,D/N,Attendance,cLI,Streak,Orig. Scheduled
1,"Thursday, Mar 28",NYY,@,HOU,W,5.0,4.0,9.0,1-0,1.0,Tied,Loáisiga,Pressly,Holmes,2:41,D,42642.0,.93,1,None
2,"Friday, Mar 29",NYY,@,HOU,W,7.0,1.0,9.0,2-0,1.0,up 0.5,Weaver,Scott,None,3:17,N,41583.0,.99,2,None
3,"Saturday, Mar 30",NYY,@,HOU,W,5.0,3.0,9.0,3-0,1.0,up 0.5,Stroman,Abreu,Holmes,2:54,N,41247.0,1.05,3,None
4,"Sunday, Mar 31",NYY,@,HOU,W,4.0,3.0,9.0,4-0,1.0,up 1.5,Burdi,Hader,Holmes,2:56,D,36908.0,1.06,4,None
5,"Monday, Apr 1",NYY,@,ARI,W,5.0,2.0,9.0,5-0,1.0,up 1.5,Weaver,Nelson,González,2:59,N,38608.0,1.04,5,None

#### Batting

In [15]:
from pybaseball import team_batting

In [16]:
# 2024
df_bat_team = team_batting(2024)
print("2024 team batting stats:\n")
df_bat_team.head()

2024 team batting stats:

,teamIDfg,Season,Team,Age,G,AB,PA,H,1B,2B,...,maxEV,HardHit,HardHit%,Events,CStr%,CSW%,xBA,xSLG,xwOBA,L-WAR
0,22,2024,LAD,29,2403,5522,6255,1423,873,291,...,119.2,1752,0.412,4253,0.158,0.265,0.252,0.444,0.338,35.9
1,15,2024,ARI,28,2436,5522,6284,1452,933,271,...,117.0,1703,0.390,4366,0.174,0.266,0.252,0.424,0.333,34.7
2,9,2024,NYY,29,2304,5450,6245,1352,857,243,...,120.0,1778,0.424,4198,0.176,0.272,0.252,0.453,0.346,34.1
3,26,2024,PHI,29,2317,5534,6166,1423,916,285,...,115.6,1679,0.398,4219,0.155,0.269,0.250,0.420,0.325,24.0
4,2,2024,BAL,28,2412,5567,6176,1391,861,262,...,114.4,1807,0.424,4264,0.159,0.267,0.247,0.434,0.328,27.6

Note: When one pulls team stats using `team_batting` as seen here, the season totals for counting stats such as home runs, for example, are what's seen in the output. For percentage stats such as `"OPS"` (on-base plus slugging), the output is instead an average. The same is true for the following two examples.

#### Pitching

In [17]:
from pybaseball import team_pitching

In [18]:
# 2024
df_pitch_team = team_pitching(2024)
print("2024 team pitching stats:\n")
df_pitch_team.head()

2024 team pitching stats:

,teamIDfg,Season,Team,Age,W,L,ERA,G,GS,CG,...,Pit+ FC,Stf+ FS,Loc+ FS,Pit+ FS,Stuff+,Location+,Pitching+,Stf+ FO,Loc+ FO,Pit+ FO
0,16,2024,ATL,29,89,73,3.49,643,162,2,...,100,116.0,99.0,106.0,101,101,101,NaN,NaN,NaN
1,11,2024,SEA,28,85,77,3.49,685,162,1,...,100,119.0,98.0,105.0,104,104,106,NaN,NaN,NaN
2,5,2024,CLE,28,92,69,3.61,754,161,0,...,114,95.0,100.0,99.0,96,99,94,NaN,NaN,NaN
3,6,2024,DET,27,86,76,3.63,666,162,1,...,98,98.0,107.0,105.0,99,101,100,NaN,NaN,NaN
4,23,2024,MIL,29,93,69,3.65,681,162,0,...,99,96.0,98.0,94.0,100,100,99,NaN,NaN,NaN

#### Fielding

In [19]:
from pybaseball import team_fielding

In [20]:
# 2024
df_field_team = team_fielding(2024)
print("2024 team fielding stats:\n")
df_field_team.head()

2024 team fielding stats:

,teamIDfg,Season,Team,G,GS,Inn,PO,A,E,FE,...,60-90%,# 60-90%,90-100%,# 90-100%,rSZ,rCERA,rTS,FRM,OAA,Range
0,14,2024,Blue Jays,2269,1459,12847.0,4282,1355,92,45,...,NaN,NaN,NaN,NaN,5,-3,26,4.1,23,21
1,7,2024,Royals,2234,1458,12853.0,4284,1423,85,44,...,NaN,NaN,NaN,NaN,2,1,-1,-2.0,36,27
2,9,2024,Yankees,2124,1458,13074.0,4358,1320,93,46,...,NaN,NaN,NaN,NaN,18,0,29,20.1,9,5
3,5,2024,Guardians,2300,1449,12852.0,4284,1377,87,49,...,NaN,NaN,NaN,NaN,19,-2,28,16.1,10,6
4,6,2024,Tigers,2251,1458,13023.0,4341,1409,80,47,...,NaN,NaN,NaN,NaN,11,-3,33,15.4,22,18

## FanGraphs Stats Collection (end of demonstration)

### Necessary Packages

In [21]:
import pandas as pd 
from pybaseball import playerid_reverse_lookup
from pybaseball import statcast_batter_exitvelo_barrels

### Setup

In [22]:
# Set some constants
START_SEASON = 2017
END_SEASON = 2024
MIN_PA = 200  # Set the minimum number of season plate appearances to include a player
SEASONS = list(range(START_SEASON, END_SEASON + 1))

### Pull (2017-2024)

In [23]:
# Pull FanGraphs stats for all MLB hitters from 2017 to 2024, excluding 2020
fangraphs_list = []
for season in SEASONS:
    if season == 2020:
        continue  # Skip 2020 COVID season
    df_f = batting_stats(season, qual = 0)  
    
    # Filter for hitters with at least 200 seasonal plate appearances
    df_f = df_f[df_f["PA"] >= MIN_PA]
    fangraphs_list.append(df_f)

# Concatenate all seasons 
fangraphs_raw = pd.concat(fangraphs_list, ignore_index = True)
print(f"Shape of FanGraphs dataset for all players initially: {fangraphs_raw.shape}\n")
fangraphs_raw.head()

Shape of FanGraphs dataset for all players initially: (2511, 320)

,IDfg,Season,Name,Team,Age,G,AB,PA,H,1B,...,maxEV,HardHit,HardHit%,Events,CStr%,CSW%,xBA,xSLG,xwOBA,L-WAR
0,15640,2017,Aaron Judge,NYY,25,155,542,678,154,75,...,121.1,186.0,0.550,338,0.157,0.290,0.287,0.668,0.450,8.7
1,5417,2017,Jose Altuve,HOU,27,153,590,662,204,137,...,109.1,145.0,0.284,511,0.161,0.233,0.291,0.477,0.360,7.5
2,13510,2017,Jose Ramirez,CLE,24,152,585,645,186,95,...,108.3,180.0,0.345,521,0.177,0.231,0.303,0.488,0.361,6.7
3,15429,2017,Kris Bryant,CHC,25,151,549,665,162,91,...,113.0,158.0,0.370,427,0.138,0.239,0.260,0.497,0.376,7.0
4,10155,2017,Mike Trout,LAA,25,114,402,507,123,62,...,114.7,128.0,0.405,316,0.193,0.255,0.294,0.589,0.424,6.4

### FanGraphs IDs

In [24]:
# Fix the FanGraphs ID column name 
fangraphs_raw = fangraphs_raw.rename(columns = {"IDfg": "fangraphs_id"})

# Ensure that FanGraphs IDs are integers
fangraphs_raw["fangraphs_id"] = pd.to_numeric(fangraphs_raw["fangraphs_id"], 
                                              errors = "coerce").astype("Int64")

# Check for missing FanGraphs IDs
missing_fg = fangraphs_raw["fangraphs_id"].isna().sum()
print(f"Missing FanGraphs IDs: {missing_fg}\n")

# Display duplicates by name and season
duplicates = fangraphs_raw[fangraphs_raw.duplicated(subset = ["Name", "Season"], 
                                                    keep = False)]
print(f"Number of duplicate name-season pairs: {duplicates.shape[0]}")

Missing FanGraphs IDs: 0

Number of duplicate name-season pairs: 0

## Statcast Data Collection

### ID Map: FanGraphs $\longrightarrow$ MLBAM (for Statcast)

In [25]:
# Collect unique FanGraphs IDs from the FanGraphs dataset
unique_fangraphs_ids = fangraphs_raw["fangraphs_id"].dropna().astype("Int64").unique().tolist()

# Look up cross-IDs for all of these FanGraphs IDs
id_map = playerid_reverse_lookup(unique_fangraphs_ids, key_type = "fangraphs")

# Keep the relevant IDs and rename the columns
id_map = id_map.rename(columns = {"key_fangraphs": "fangraphs_id",
                                  "key_mlbam": "mlbam_id"})
id_map = id_map[["fangraphs_id", "mlbam_id"]]
print("IDs:\n")
id_map.head()

IDs:

   fangraphs_id  mlbam_id
0         24655    680911
1         19470    669242
2         19906    660636
3         23565    676914
4          8001    434670

### New MLBAM ID Column, FanGraphs Dataset Merge

In [26]:
# Left-join the MLBAM ID column to the FanGraphs dataset
fangraphs_raw = fangraphs_raw.merge(id_map, on = "fangraphs_id", how = "left")

# Ensure that MLBAM IDs are integers
fangraphs_raw["mlbam_id"] = pd.to_numeric(fangraphs_raw["mlbam_id"], 
                                          errors = "coerce").astype("Int64")

# Check for missing MLBAM IDs
missing_mlbam = fangraphs_raw["mlbam_id"].isna().sum()
print(f"Missing MLBAM IDs: {missing_mlbam}\n")
fangraphs_raw.head()

Missing MLBAM IDs: 11

,fangraphs_id,Season,Name,Team,Age,G,AB,PA,H,1B,...,HardHit,HardHit%,Events,CStr%,CSW%,xBA,xSLG,xwOBA,L-WAR,mlbam_id
0,15640,2017,Aaron Judge,NYY,25,155,542,678,154,75,...,186.0,0.550,338,0.157,0.290,0.287,0.668,0.450,8.7,592450
1,5417,2017,Jose Altuve,HOU,27,153,590,662,204,137,...,145.0,0.284,511,0.161,0.233,0.291,0.477,0.360,7.5,514888
2,13510,2017,Jose Ramirez,CLE,24,152,585,645,186,95,...,180.0,0.345,521,0.177,0.231,0.303,0.488,0.361,6.7,608070
3,15429,2017,Kris Bryant,CHC,25,151,549,665,162,91,...,158.0,0.370,427,0.138,0.239,0.260,0.497,0.376,7.0,592178
4,10155,2017,Mike Trout,LAA,25,114,402,507,123,62,...,128.0,0.405,316,0.193,0.255,0.294,0.589,0.424,6.4,545361

### Players with No MLBAM ID

In [27]:
# Remove players with no MLBAM ID since they have no Statcast data
before = fangraphs_raw.shape[0]
fangraphs_raw = fangraphs_raw.dropna(subset = ["mlbam_id"])
fangraphs_raw["mlbam_id"] = fangraphs_raw["mlbam_id"].astype("Int64")
after = fangraphs_raw.shape[0]

# Report how many players were removed
print(f"Removed {before - after} players with missing MLBAM IDs!\n")
print(f"Remaining rows: {after}\n")
fangraphs_raw.head()

Removed 11 players with missing MLBAM IDs!

Remaining rows: 2500

,fangraphs_id,Season,Name,Team,Age,G,AB,PA,H,1B,...,HardHit,HardHit%,Events,CStr%,CSW%,xBA,xSLG,xwOBA,L-WAR,mlbam_id
0,15640,2017,Aaron Judge,NYY,25,155,542,678,154,75,...,186.0,0.550,338,0.157,0.290,0.287,0.668,0.450,8.7,592450
1,5417,2017,Jose Altuve,HOU,27,153,590,662,204,137,...,145.0,0.284,511,0.161,0.233,0.291,0.477,0.360,7.5,514888
2,13510,2017,Jose Ramirez,CLE,24,152,585,645,186,95,...,180.0,0.345,521,0.177,0.231,0.303,0.488,0.361,6.7,608070
3,15429,2017,Kris Bryant,CHC,25,151,549,665,162,91,...,158.0,0.370,427,0.138,0.239,0.260,0.497,0.376,7.0,592178
4,10155,2017,Mike Trout,LAA,25,114,402,507,123,62,...,128.0,0.405,316,0.193,0.255,0.294,0.589,0.424,6.4,545361

### NOW FanGraphs Dataset Save

In [28]:
# Save the dataset to a CSV file
fangraphs_raw.to_csv("../Data/Raw/FanGraphs_Raw.csv", index = False)

### Pull (2017-2024)

In [29]:
# Pull Statcast aggregates for all hitters from 2017 to 2024, excluding 2020
statcast_list = []
for season in SEASONS:
    if season == 2020:  
        continue  # Skip 2020 COVID season
    df_s = statcast_batter_exitvelo_barrels(season)
    df_s["Season"] = season
    statcast_list.append(df_s)

# Concatenate all seasons 
statcast_raw = pd.concat(statcast_list, ignore_index = True)
print(f"Shape of Statcast dataset for all players initially: {statcast_raw.shape}\n")
statcast_raw.head()

Shape of Statcast dataset for all players initially: (1749, 19)

,"last_name, first_name",player_id,attempts,avg_hit_angle,anglesweetspotpercent,max_hit_speed,avg_hit_speed,ev50,fbld,gb,max_distance,avg_distance,avg_hr_distance,ev95plus,ev95percent,barrels,brl_percent,brl_pa,Season
0,"Inciarte, Ender",542255,575,10.2,34.3,102.7,82.8,92.3,87.5,78.7,434,152,382.0,75,13.1,3,0.5,0.4,2017
1,"Strange-Gordon, Dee",543829,566,2.4,27.7,104.1,81.6,91.7,85.9,79.6,395,123,380.0,63,11.2,1,0.2,0.1,2017
2,"Lindor, Francisco",596019,566,14.6,32.2,111.7,89.1,99.1,92.8,85.4,456,192,401.0,203,35.9,40,7.1,5.5,2017
3,"Betts, Mookie",605141,554,14.3,31.9,111.7,88.4,99.3,92.9,87.4,434,179,396.0,208,37.9,25,4.5,3.5,2017
4,"Cabrera, Melky",466320,554,8.9,33.6,113.6,88.3,98.7,90.9,87.5,420,161,393.0,194,35.1,21,3.8,3.2,2017

Note: The Statcast batting dataset is smaller (in terms of rows) than the FanGraphs batting dataset because Statcast only includes players who generated measurable batted-ball events in a given season. While FanGraphs reports statistics for every hitter who recorded plate appearances, Statcast requires actual tracked contact, such as exit velocity or launch angle, to generate a profile. As a result, players with limited playing time, few balls in play, injury-shortened seasons, or data inconsistencies may be present in FanGraphs but missing from Statcast. This discrepancy is expected and does not affect the analysis, since all meaningful comparison hitters, including Aaron Judge, have complete Statcast data.

### Row Removal, Statcast Dataset Save

In [30]:
# Keep Statcast rows only for hitters who appear in the FanGraphs dataset
valid_mlbam_ids = fangraphs_raw["mlbam_id"].unique().tolist()
statcast_raw = statcast_raw[statcast_raw["player_id"].isin(valid_mlbam_ids)]
print(f"Statcast rows after filtering to hitters with FanGraphs data: {statcast_raw.shape[0]}\n")

# Save the dataset to a CSV file
statcast_raw.to_csv("../Data/Raw/Statcast_Raw.csv", index = False)

Statcast rows after filtering to hitters with FanGraphs data: 1746